### ISSUE TITLE
Accuracy가 낮아졌습니다

### ISSUE THREAD

**Issue by ppuingppuing** [Ilak0121/com_lec#3]
Accuracy가 0.805였는데 현재 0.104입니다!

**Comment by Ilak0121** [comment]
헐 클났다

2018년 11월 28일 (수) 오후 3:30, ppuing <notifications@github.com>님이 작성:

**Comment by ppuingppuing** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ해결했당 미안
