### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by Ilak0121** [Ilak0121/com_lec#4]
backtrace 
 fread
 main

seem to be malloced memory address is not good

**Comment by ppuingppuing** [comment]
🤦‍♂️

**Comment by ppuingppuing** [comment]
But they are just good at normal PCs

**Comment by Ilak0121** [comment]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Android/full_avl8890/avl8890:6.0.1/MMB29T/hanback112281616:eng/test-keys'
Revision: '0'
ABI: 'arm64'
pid: 4549, tid: 4549, name: recognition_seq  >>> ./recognition_seq <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x58
    x0   0000000000000000  x1   0000000000000000  x2   0000000002562500  x3   0000000000000000
    x4   0000000000000000  x5   00000000ffffffff  x6   0000000000000000  x7   0000000000000000
    x8   0000000000000038  x9   00000000000011c5  x10  0000007f892d751c  x11  0000000000000000
    x12  0000000000004001  x13  0000007f892d74e0  x14  00000000ffffffff  x15  0000007f892d74e0
    x16  0000007f893a0578  x17  0000007f89266fcc  x18  0000007f892d74e0  x19  0000007fffc26598
    x20  0000000000000000  x21  0000000000000003  x22  0000007f7eec0000  x23  0000000009589400
    x24  0000000000000004  x25  0000000000000000  x26  0000000000000000  x27  0000000000000000
    x28  0000000000000000  x29  0000007fffc26390  x30  0000007f8938fc88
    sp   0000007fffc26390  pc   0000007f89267028  pstate 0000000080000000
    v0   0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a  v1   616d695f5453494e4d000a64253d6874
    v2   62616c5f5453494e4d006e69622e6567  v3   00000000000000000000040000000000
    v4   00000000000000000000000000000000  v5   40100401401004014010040140100401
    v6   00000000000004000000000000000400  v7   00000000000001f100000000000001f1
    v8   00000000000000000000000000000000  v9   00000000000000000000000000000000
    v10  00000000000000000000000000000000  v11  00000000000000000000000000000000
    v12  00000000000000000000000000000000  v13  00000000000000000000000000000000
    v14  00000000000000000000000000000000  v15  00000000000000000000000000000000
    v16  00000000000051f100000000000041f1  v17  00000000000000000000000000000000
    v18  00000000000051f100000000000041f1  v19  00000000000000000000000000000000
    v20  00000000000000000000000000000000  v21  00000000000000000000000000000000
    v22  00000000000000000000000000000000  v23  00000000000000000000000000000000
    v24  00000000000000000000000000000000  v25  00000000000000000000000000000000
    v26  00000000000000000000000000000000  v27  00000000000000000000000000000000
    v28  00000000000000000000000000000000  v29  00000000000000000000000000000000
    v30  00000000000000000000000000000000  v31  00000000000000000000000000000000
    fpsr 00000000  fpcr 00000000

backtrace:
    #00 pc 0000000000073028  /system/lib64/libc.so (fread+92)
    #01 pc 0000000000001c84  /data/local/tmp/recognition_seq (main+604)

stack:
         0000007fffc26310  0000040000000000
         0000007fffc26318  0000000000000000
         0000007fffc26320  0000000000000000
         0000007fffc26328  0000000000000000
         0000007fffc26330  4010040140100401
         0000007fffc26338  4010040140100401
         0000007fffc26340  0000000000000400
         0000007fffc26348  0000000000000400
         0000007fffc26350  00000000000001f1
         0000007fffc26358  00000000000001f1
         0000007fffc26360  00000000000001b6
         0000007fffc26368  0000000000000001
         0000007fffc26370  0000000000002000
         0000007fffc26378  0000000000004000
         0000007fffc26380  0000000000000000
         0000007fffc26388  0000000000000000
    #00  0000007fffc26390  0000007fffc26500  [stack]
         0000007fffc26398  0000007f8938fc88  /data/local/tmp/recognition_seq (main+608)
         0000007fffc263a0  0000007fffc26598  [stack]
         0000007fffc263a8  0000007fffc26578  [stack]
         0000007fffc263b0  0000000000000003
         0000007fffc263b8  0000007f8938fa28  /data/local/tmp/recognition_seq (main)
         0000007fffc263c0  0000000000000000
         0000007fffc263c8  0000000000000000
    #01  0000007fffc263d0  0000000000000000
         0000007fffc263d8  0000000000000000
         0000007fffc263e0  0000000000000000
         0000007fffc263e8  0000000000000000
         0000007fffc263f0  0000000000000000
         0000007fffc263f8  0000000000000000
         0000007fffc26400  0000007f893466f0  /system/bin/linker64
         0000007fffc26408  00000000000000e6
         0000007fffc26410  0000000000000000
         0000007fffc26418  0000000000000000
         0000007fffc26420  000000000000d70a
         0000007fffc26428  0000001100000007
         0000007fffc26430  0000000000000001
         0000007fffc26438  0000000000000001
         0000007fffc26440  0000000000000000
         0000007fffc26448  0000000000000000

memory near x2:
    00000000025624e0 ---------------- ----------------  ................
    00000000025624f0 ---------------- ----------------  ................
    0000000002562500 ---------------- ----------------  ................
    0000000002562510 ---------------- ----------------  ................
    0000000002562520 ---------------- ----------------  ................
    0000000002562530 ---------------- ----------------  ................
    0000000002562540 ---------------- ----------------  ................
    0000000002562550 ---------------- ----------------  ................
    0000000002562560 ---------------- ----------------  ................
    0000000002562570 ---------------- ----------------  ................
    0000000002562580 ---------------- ----------------  ................
    0000000002562590 ---------------- ----------------  ................
    00000000025625a0 ---------------- ----------------  ................
    00000000025625b0 ---------------- ----------------  ................
    00000000025625c0 ---------------- ----------------  ................
    00000000025625d0 ---------------- ----------------  ................

memory near x5:
    00000000ffffffd8 ---------------- ----------------  ................
    00000000ffffffe8 ---------------- ----------------  ................
    00000000fffffff8 ---------------- ----------------  ................
    0000000100000008 ---------------- ----------------  ................
    0000000100000018 ---------------- ----------------  ................
    0000000100000028 ---------------- ----------------  ................
    0000000100000038 ---------------- ----------------  ................
    0000000100000048 ---------------- ----------------  ................
    0000000100000058 ---------------- ----------------  ................
    0000000100000068 ---------------- ----------------  ................
    0000000100000078 ---------------- ----------------  ................
    0000000100000088 ---------------- ----------------  ................
    0000000100000098 ---------------- ----------------  ................
    00000001000000a8 ---------------- ----------------  ................
    00000001000000b8 ---------------- ----------------  ................
    00000001000000c8 ---------------- ----------------  ................

memory near x9:
    00000000000011a0 ---------------- ----------------  ................
    00000000000011b0 ---------------- ----------------  ................
    00000000000011c0 ---------------- ----------------  ................
    00000000000011d0 ---------------- ----------------  ................
    00000000000011e0 ---------------- ----------------  ................
    00000000000011f0 ---------------- ----------------  ................
    0000000000001200 ---------------- ----------------  ................
    0000000000001210 ---------------- ----------------  ................
    0000000000001220 ---------------- ----------------  ................
    0000000000001230 ---------------- ----------------  ................
    0000000000001240 ---------------- ----------------  ................
    0000000000001250 ---------------- ----------------  ................
    0000000000001260 ---------------- ----------------  ................
    0000000000001270 ---------------- ----------------  ................
    0000000000001280 ---------------- ----------------  ................
    0000000000001290 ---------------- ----------------  ................

memory near x10:
    0000007f892d74f8 0000000000000000 0000000000000000  ................
    0000007f892d7508 0000000000000000 0000000000000000  ................
    0000007f892d7518 0000000000004000 0000000000000000  .@..............
    0000007f892d7528 0000000000000000 0000000000000000  ................
    0000007f892d7538 0000000000000000 0000000000000001  ................
    0000007f892d7548 0000000000000000 0000000000000000  ................
    0000007f892d7558 0000000000000000 0000000000000000  ................
    0000007f892d7568 0000000000000000 0000000000000000  ................
    0000007f892d7578 0000000000000000 0000000000004000  .........@......
    0000007f892d7588 0000000000000000 0000000000000000  ................
    0000007f892d7598 0000000000000000 0000000000000000  ................
    0000007f892d75a8 0000000000000001 0000000000000000  ................
    0000007f892d75b8 0000000000000000 0000000000000000  ................
    0000007f892d75c8 0000000000000000 0000000000000000  ................
    0000007f892d75d8 0000000000000000 0000000000000000  ................
    0000007f892d75e8 0000000000004000 0000000000000000  .@..............

memory near x12:
    0000000000003fe0 ---------------- ----------------  ................
    0000000000003ff0 ---------------- ----------------  ................
    0000000000004000 ---------------- ----------------  ................
    0000000000004010 ---------------- ----------------  ................
    0000000000004020 ---------------- ----------------  ................
    0000000000004030 ---------------- ----------------  ................
    0000000000004040 ---------------- ----------------  ................
    0000000000004050 ---------------- ----------------  ................
    0000000000004060 ---------------- ----------------  ................
    0000000000004070 ---------------- ----------------  ................
    0000000000004080 ---------------- ----------------  ................
    0000000000004090 ---------------- ----------------  ................
    00000000000040a0 ---------------- ----------------  ................
    00000000000040b0 ---------------- ----------------  ................
    00000000000040c0 ---------------- ----------------  ................
    00000000000040d0 ---------------- ----------------  ................

memory near x13:
    0000007f892d74c0 0000000000000000 0000000000000000  ................
    0000007f892d74d0 0000000000000000 0000000000000000  ................
    0000007f892d74e0 0000000000000000 0000000000000000  ................
    0000007f892d74f0 0000000000000000 0000000000000000  ................
    0000007f892d7500 0000000000000000 0000000000000000  ................
    0000007f892d7510 0000000000000000 0000000000004000  .........@......
    0000007f892d7520 0000000000000000 0000000000000000  ................
    0000007f892d7530 0000000000000000 0000000000000000  ................
    0000007f892d7540 0000000000000001 0000000000000000  ................
    0000007f892d7550 0000000000000000 0000000000000000  ................
    0000007f892d7560 0000000000000000 0000000000000000  ................
    0000007f892d7570 0000000000000000 0000000000000000  ................
    0000007f892d7580 0000000000004000 0000000000000000  .@..............
    0000007f892d7590 0000000000000000 0000000000000000  ................
    0000007f892d75a0 0000000000000000 0000000000000001  ................
    0000007f892d75b0 0000000000000000 0000000000000000  ................

memory near x14:
    00000000ffffffd8 ---------------- ----------------  ................
    00000000ffffffe8 ---------------- ----------------  ................
    00000000fffffff8 ---------------- ----------------  ................
    0000000100000008 ---------------- ----------------  ................
    0000000100000018 ---------------- ----------------  ................
    0000000100000028 ---------------- ----------------  ................
    0000000100000038 ---------------- ----------------  ................
    0000000100000048 ---------------- ----------------  ................
    0000000100000058 ---------------- ----------------  ................
    0000000100000068 ---------------- ----------------  ................
    0000000100000078 ---------------- ----------------  ................
    0000000100000088 ---------------- ----------------  ................
    0000000100000098 ---------------- ----------------  ................
    00000001000000a8 ---------------- ----------------  ................
    00000001000000b8 ---------------- ----------------  ................
    00000001000000c8 ---------------- ----------------  ................

memory near x15:
    0000007f892d74c0 0000000000000000 0000000000000000  ................
    0000007f892d74d0 0000000000000000 0000000000000000  ................
    0000007f892d74e0 0000000000000000 0000000000000000  ................
    0000007f892d74f0 0000000000000000 0000000000000000  ................
    0000007f892d7500 0000000000000000 0000000000000000  ................
    0000007f892d7510 0000000000000000 0000000000004000  .........@......
    0000007f892d7520 0000000000000000 0000000000000000  ................
    0000007f892d7530 0000000000000000 0000000000000000  ................
    0000007f892d7540 0000000000000001 0000000000000000  ................
    0000007f892d7550 0000000000000000 0000000000000000  ................
    0000007f892d7560 0000000000000000 0000000000000000  ................
    0000007f892d7570 0000000000000000 0000000000000000  ................
    0000007f892d7580 0000000000004000 0000000000000000  .@..............
    0000007f892d7590 0000000000000000 0000000000000000  ................
    0000007f892d75a0 0000000000000000 0000000000000001  ................
    0000007f892d75b0 0000000000000000 0000000000000000  ................

memory near x16:
    0000007f893a0558 0000000000000000 0000007f892f0910  ........../.....
    0000007f893a0568 0000007f8924c9c0 0000007f8920faa0  ..$....... .....
    0000007f893a0578 0000007f89266fcc 0000007f89249008  .o&.......$.....
    0000007f893a0588 0000007f8920ea50 0000007f8924a178  P. .....x.$.....
    0000007f893a0598 0000007f8920fb08 0000007f8924a068  .. .....h.$.....
    0000007f893a05a8 0000007f8920fc34 0000007f89211b14  4. .......!.....
    0000007f893a05b8 0000007f89267644 0000000000000000  Dv&.............
    0000007f893a05c8 0000000000000000 0000000000000000  ................
    0000007f893a05d8 0000000000000000 000000000000458f  .........E......
    0000007f893a05e8 000000001a235ead 0000000000000000  .^#.............
    0000007f893a05f8 0000000000000000 0000000000000000  ................
    0000007f893a0608 0000000000000000 0000000000000000  ................
    0000007f893a0618 0000000000000000 0000000000000000  ................
    0000007f893a0628 0000000000000000 0000000000000000  ................
    0000007f893a0638 0000000000000000 0000000000000000  ................
    0000007f893a0648 0000000000000000 0000000000000000  ................

memory near x17:
    0000007f89266fa8 f902fd7af942fd6c f9400b5af900019a  l.B.z.......Z.@.
    0000007f89266fb8 97ffff2717ffff9f aa1703e017ffff8c  ....'...........
    0000007f89266fc8 a9bc7bfd17ffffbf eb05003fb2407fe5  .....{....@.?...
    0000007f89266fd8 a90363f7910003fd 1a9f97e1aa0103f8  .....c..........
    0000007f89266fe8 1a9f97e4eb05005f a9025bf5a90153f3  _........S...[..
    0000007f89266ff8 2a040020aa0003f6 340000c0aa0303f4  .... ..*.......4
    0000007f89267008 92800003b40000b8 eb06005f9ad80866  ........f..._...
    0000007f89267018 9b027f1754000a68 b4000577d2800000  h..T........w...
    0000007f89267028 3941816af9402e8b b940316c3500090a  ..@.j.A9...5l1@.
    0000007f89267038 3500006c9100416d b90021ae1280000e  mA..l..5.....!..
    0000007f89267048 37f809efb9400a8f b40009f0f9400e90  ..@....7..@.....
    0000007f89267058 14000006aa1703f5 eb1e02bff940129e  ..........@.....
    0000007f89267068 97ff9721540003e8 b9800a9335000260  ...T!...`..5....
    0000007f89267078 f9400281aa1603e0 9a9392b3eb1302bf  ......@.........
    0000007f89267088 8b1302d6aa1303e2 f940029197fe9280  ..............@.
    0000007f89267098 b9400a92eb1302b5 8b130225aa1403e0  ......@.....%...

memory near x18:
    0000007f892d74c0 0000000000000000 0000000000000000  ................
    0000007f892d74d0 0000000000000000 0000000000000000  ................
    0000007f892d74e0 0000000000000000 0000000000000000  ................
    0000007f892d74f0 0000000000000000 0000000000000000  ................
    0000007f892d7500 0000000000000000 0000000000000000  ................
    0000007f892d7510 0000000000000000 0000000000004000  .........@......
    0000007f892d7520 0000000000000000 0000000000000000  ................
    0000007f892d7530 0000000000000000 0000000000000000  ................
    0000007f892d7540 0000000000000001 0000000000000000  ................
    0000007f892d7550 0000000000000000 0000000000000000  ................
    0000007f892d7560 0000000000000000 0000000000000000  ................
    0000007f892d7570 0000000000000000 0000000000000000  ................
    0000007f892d7580 0000000000004000 0000000000000000  .@..............
    0000007f892d7590 0000000000000000 0000000000000000  ................
    0000007f892d75a0 0000000000000000 0000000000000001  ................
    0000007f892d75b0 0000000000000000 0000000000000000  ................

memory near x19:
    0000007fffc26578 0000007fffc26bbc 0000007fffc26bce  .k.......k......
    0000007fffc26588 0000007fffc26bdc 0000000000000000  .k..............
    0000007fffc26598 0000007fffc26be7 0000007fffc26bfb  .k.......k......
    0000007fffc265a8 0000007fffc26c0e 0000007fffc26c22  .l......"l......
    0000007fffc265b8 0000007fffc26c60 0000007fffc26c6b  `l......kl......
    0000007fffc265c8 0000007fffc26c75 0000007fffc26c8a  ul.......l......
    0000007fffc265d8 0000007fffc26c95 0000007fffc26caa  .l.......l......
    0000007fffc265e8 0000007fffc26cbd 0000007fffc26cd4  .l.......l......
    0000007fffc265f8 0000007fffc26cef 0000007fffc26e97  .l.......n......
    0000007fffc26608 0000007fffc26eb1 0000007fffc26ec8  .n.......n......
    0000007fffc26618 0000007fffc26ed9 0000007fffc26ef2  .n.......n......
    0000007fffc26628 0000007fffc26f0b 0000007fffc26f48  .o......Ho......
    0000007fffc26638 0000007fffc26fc7 0000000000000000  .o..............
    0000007fffc26648 0000000000000021 0000007f8939f000  !.........9.....
    0000007fffc26658 0000000000000010 00000000000000ff  ................
    0000007fffc26668 0000000000000006 0000000000001000  ................

memory near x22:
    0000007f7eebffe0 0000000000000000 0000000000000000  ................
    0000007f7eebfff0 0000000000000000 0000000000000000  ................
    0000007f7eec0000 0000000000000000 0000000000000000  ................
    0000007f7eec0010 0000000000000000 0000000000000000  ................
    0000007f7eec0020 0000000000000000 0000000000000000  ................
    0000007f7eec0030 0000000000000000 0000000000000000  ................
    0000007f7eec0040 0000000000000000 0000000000000000  ................
    0000007f7eec0050 0000000000000000 0000000000000000  ................
    0000007f7eec0060 0000000000000000 0000000000000000  ................
    0000007f7eec0070 0000000000000000 0000000000000000  ................
    0000007f7eec0080 0000000000000000 0000000000000000  ................
    0000007f7eec0090 0000000000000000 0000000000000000  ................
    0000007f7eec00a0 0000000000000000 0000000000000000  ................
    0000007f7eec00b0 0000000000000000 0000000000000000  ................
    0000007f7eec00c0 0000000000000000 0000000000000000  ................
    0000007f7eec00d0 0000000000000000 0000000000000000  ................

memory near x23:
    00000000095893e0 ---------------- ----------------  ................
    00000000095893f0 ---------------- ----------------  ................
    0000000009589400 ---------------- ----------------  ................
    0000000009589410 ---------------- ----------------  ................
    0000000009589420 ---------------- ----------------  ................
    0000000009589430 ---------------- ----------------  ................
    0000000009589440 ---------------- ----------------  ................
    0000000009589450 ---------------- ----------------  ................
    0000000009589460 ---------------- ----------------  ................
    0000000009589470 ---------------- ----------------  ................
    0000000009589480 ---------------- ----------------  ................
    0000000009589490 ---------------- ----------------  ................
    00000000095894a0 ---------------- ----------------  ................
    00000000095894b0 ---------------- ----------------  ................
    00000000095894c0 ---------------- ----------------  ................
    00000000095894d0 ---------------- ----------------  ................

memory near x29:
    0000007fffc26370 0000000000002000 0000000000004000  . .......@......
    0000007fffc26380 0000000000000000 0000000000000000  ................
    0000007fffc26390 0000007fffc26500 0000007f8938fc88  .e........8.....
    0000007fffc263a0 0000007fffc26598 0000007fffc26578  .e......xe......
    0000007fffc263b0 0000000000000003 0000007f8938fa28  ........(.8.....
    0000007fffc263c0 0000000000000000 0000000000000000  ................
    0000007fffc263d0 0000000000000000 0000000000000000  ................
    0000007fffc263e0 0000000000000000 0000000000000000  ................
    0000007fffc263f0 0000000000000000 0000000000000000  ................
    0000007fffc26400 0000007f893466f0 00000000000000e6  .f4.............
    0000007fffc26410 0000000000000000 0000000000000000  ................
    0000007fffc26420 000000000000d70a 0000001100000007  ................
    0000007fffc26430 0000000000000001 0000000000000001  ................
    0000007fffc26440 0000000000000000 0000000000000000  ................
    0000007fffc26450 0000007fffc264e0 00030d4089346000  .d.......`4.@...
    0000007fffc26460 0000004000000002 0000007f89387e20  ....@... ~8.....

memory near x30:
    0000007f8938fc68 b27e03e197fffb8e f2a04ac2d284a002  ......~......J..
    0000007f8938fc78 f85d83a0f81983a0 97fffb73f85983a3  ......]...Y.s...
    0000007f8938fc88 f90023e0f85983a1 97fffb73aa0103e0  ..Y..#......s...
    0000007f8938fc98 91085c21b0000001 91076042b0000002  ....!\......B`..
    0000007f8938fca8 aa0103e0b9003fe0 97fffb7baa0203e1  .?..........{...
    0000007f8938fcb8 d2986a02b27e03e1 f85b03a0f81983a0  ..~..j........[.
    0000007f8938fcc8 97fffb61f85983a3 f9001be0f85983a1  ..Y.a.....Y.....
    0000007f8938fcd8 97fffb61aa0103e0 d101e3a1320003e8  ....a......2....
    0000007f8938fce8 2a0803e0b9002fe0 f85d83a197fffb74  ./.....*t.....].
    0000007f8938fcf8 b94093e8f85d03a2 f85b83a4b94097e3  ..]...@...@...[.
    0000007f8938fd08 b9002be0f85c83a5 aa0203e1aa0103e0  ..\..+..........
    0000007f8938fd18 97fffb8f2a0803e2 d10223a1320003e0  ...*.......2.#..
    0000007f8938fd28 910263e197fffb66 d101e3a2d10223a4  f....c...#......
    0000007f8938fd38 aa0103e0b90027e0 940000b8aa0403e1  .'..............
    0000007f8938fd48 b81ac3bfb81a83bf 52986a08b90023e0  .........#...j.R
    0000007f8938fd58 6b08013fb85ac3a9 f85b03a8540002ea  ..Z.?..k...T..[.

code around pc:
    0000007f89267008 92800003b40000b8 eb06005f9ad80866  ........f..._...
    0000007f89267018 9b027f1754000a68 b4000577d2800000  h..T........w...
    0000007f89267028 3941816af9402e8b b940316c3500090a  ..@.j.A9...5l1@.
    0000007f89267038 3500006c9100416d b90021ae1280000e  mA..l..5.....!..
    0000007f89267048 37f809efb9400a8f b40009f0f9400e90  ..@....7..@.....
    0000007f89267058 14000006aa1703f5 eb1e02bff940129e  ..........@.....
    0000007f89267068 97ff9721540003e8 b9800a9335000260  ...T!...`..5....
    0000007f89267078 f9400281aa1603e0 9a9392b3eb1302bf  ......@.........
    0000007f89267088 8b1302d6aa1303e2 f940029197fe9280  ..............@.
    0000007f89267098 b9400a92eb1302b5 8b130225aa1403e0  ......@.....%...
    0000007f892670a8 4b130241f9000285 54fffd61b9000a81  ....A..K....a..T
    0000007f892670b8 f9402e8bd2800015 3500040c3941816c  ......@.l.A9...5
    0000007f892670c8 9ad80a80cb1502f4 a9425bf5a94153f3  .........SA..[B.
    0000007f892670d8 a8c47bfda94363f7 b9401284d65f03c0  .cC..{...._...@.
    0000007f892670e8 b900128032130080 eb0602b514000003  ...2............
    0000007f892670f8 f940228354fffe00 f9401a80aa1603e1  ...T."@.......@.

code around sp:
    0000007fffc26370 0000000000002000 0000000000004000  . .......@......
    0000007fffc26380 0000000000000000 0000000000000000  ................
    0000007fffc26390 0000007fffc26500 0000007f8938fc88  .e........8.....
    0000007fffc263a0 0000007fffc26598 0000007fffc26578  .e......xe......
    0000007fffc263b0 0000000000000003 0000007f8938fa28  ........(.8.....
    0000007fffc263c0 0000000000000000 0000000000000000  ................
    0000007fffc263d0 0000000000000000 0000000000000000  ................
    0000007fffc263e0 0000000000000000 0000000000000000  ................
    0000007fffc263f0 0000000000000000 0000000000000000  ................
    0000007fffc26400 0000007f893466f0 00000000000000e6  .f4.............
    0000007fffc26410 0000000000000000 0000000000000000  ................
    0000007fffc26420 000000000000d70a 0000001100000007  ................
    0000007fffc26430 0000000000000001 0000000000000001  ................
    0000007fffc26440 0000000000000000 0000000000000000  ................
    0000007fffc26450 0000007fffc264e0 00030d4089346000  .d.......`4.@...
    0000007fffc26460 0000004000000002 0000007f89387e20  ....@... ~8.....

memory map: (fault address prefixed with --->)
--->Fault address falls at 00000000'00000058 before any mapped regions
    0000007f'7edc0000-0000007f'890bffff rw-         0   a300000  [anon:libc_malloc]
    0000007f'890d0000-0000007f'891a6fff r-x         0     d7000  /system/lib64/libc++.so (BuildId: 9631018376ca967f39d325f48c0a88a9) (load base 0x9000)
    0000007f'891a7000-0000007f'891b5fff ---         0      f000
    0000007f'891b6000-0000007f'891bcfff r--     df000      7000  /system/lib64/libc++.so
    0000007f'891bd000-0000007f'891bdfff rw-     e6000      1000  /system/lib64/libc++.so
    0000007f'891be000-0000007f'891c0fff rw-         0      3000
    0000007f'891c1000-0000007f'891c2fff r-x         0      2000  /system/lib64/libnetd_client.so (BuildId: ffbfd200a25e14388b860ab1b407bdc5)
    0000007f'891c3000-0000007f'891d1fff ---         0      f000
    0000007f'891d2000-0000007f'891d2fff r--      1000      1000  /system/lib64/libnetd_client.so
    0000007f'891d3000-0000007f'891d3fff rw-      2000      1000  /system/lib64/libnetd_client.so
    0000007f'891d4000-0000007f'891f3fff r--         0     20000  /dev/__properties__
    0000007f'891f4000-0000007f'892b5fff r-x         0     c2000  /system/lib64/libc.so (BuildId: 09cf7a69f444849ebf3ed9364140ee23)
    0000007f'892b6000-0000007f'892c4fff ---         0      f000
    0000007f'892c5000-0000007f'892cafff r--     c1000      6000  /system/lib64/libc.so
    0000007f'892cb000-0000007f'892cdfff rw-     c7000      3000  /system/lib64/libc.so
    0000007f'892ce000-0000007f'892dbfff rw-         0      e000
    0000007f'892dc000-0000007f'89313fff r-x         0     38000  /system/lib64/libm.so (BuildId: 96ccce4a25c0658bda2e0f7c54aa26b0)
    0000007f'89314000-0000007f'89323fff ---         0     10000
    0000007f'89324000-0000007f'89324fff r--     38000      1000  /system/lib64/libm.so
    0000007f'89325000-0000007f'89325fff rw-     39000      1000  /system/lib64/libm.so
    0000007f'89326000-0000007f'89345fff r--         0     20000  /dev/__properties__
    0000007f'89346000-0000007f'89376fff r-x         0     31000  /system/bin/linker64 (BuildId: 381b3a4c8c035b7ae75aa09f4d4965e4)
    0000007f'89384000-0000007f'89384fff rw-         0      1000  [anon:linker_alloc_vector]
    0000007f'89386000-0000007f'89386fff rw-         0      1000  [anon:linker_alloc_vector]
    0000007f'89387000-0000007f'89387fff r--     31000      1000  /system/bin/linker64
    0000007f'89388000-0000007f'89389fff rw-     32000      2000  /system/bin/linker64
    0000007f'8938a000-0000007f'8938dfff rw-         0      4000
    0000007f'8938e000-0000007f'89390fff r-x         0      3000  /data/local/tmp/recognition_seq
    0000007f'89391000-0000007f'89391fff rw-         0      1000  [anon:linker_alloc_64]
    0000007f'89393000-0000007f'89393fff rw-         0      1000  [anon:linker_alloc_vector]
    0000007f'89394000-0000007f'89394fff r--         0      1000
    0000007f'89395000-0000007f'89395fff r--         0      1000  [anon:linker_alloc]
    0000007f'89396000-0000007f'89396fff rw-         0      1000  [anon:linker_alloc]
    0000007f'89397000-0000007f'89397fff r--         0      1000  [anon:linker_alloc]
    0000007f'89398000-0000007f'89398fff r--         0      1000
    0000007f'89399000-0000007f'89399fff ---         0      1000
    0000007f'8939a000-0000007f'8939dfff rw-         0      4000  [anon:thread signal stack]
    0000007f'8939e000-0000007f'8939efff r--         0      1000  [vvar]
    0000007f'8939f000-0000007f'8939ffff r-x         0      1000  [vdso]
    0000007f'893a0000-0000007f'893a0fff rw-      2000      1000  /data/local/tmp/recognition_seq
    0000007f'ffc06000-0000007f'ffc26fff rw-         0     21000  [stack]
--------- tail end of log main
01-01 16:56:36.583  4549  4549 W linker  : ./recognition_seq: unsupported flags DT_FLAGS_1=0x8000000
--------- log main
01-01 16:56:36.583  4549  4549 W linker  : ./recognition_seq: unsupported flags DT_FLAGS_1=0x8000000

Tombstone written to: /data/tombstones/tombstone_08

**Comment by ppuingppuing** [comment]
필요한 파일을 같이 넣어주지 않아서 생기는 문제였습니다!
예외처리의 중요성을 다시한번 깨닫는 순간

**Comment by Ilak0121** [comment]
@ppuingppuing 아예 헤더를 만드려고 예외처리하는 함수들 모아서
